<div class="mh-full-screen d-flex align-items-center dark-overlay"><img src="https://portalhaus.s3.us-east-2.amazonaws.com/homefacebook.jpg" alt="Coming Soon" class="bg-image">
      <div class="container text-white text-center text-lg overlay-content py-6 py-lg-0">
        <h1 class="text-hide mx-auto mb-6">Error 500<img src="https://d19m59y37dris4.cloudfront.net/directory/1-4/img/coming-soon.png" alt="Coming Soon" class="img-fluid"></h1>
        <h3 class="mb-5 text-shadow">Error 500. No encontramos la página</h3>
        <p class="font-weight-light mb-4"><i class="fas fa-map-marker-alt mr-2"></i> Portalhaus SpA | Chile</p>
        <ul class="list-inline">
          <li class="list-inline-item"><a href="https://www.facebook.com/portalhauscl-110683013978502" target="_blank" title="facebook" class="text-white"><i class="fab fa-facebook">           </i></a></li>
          <li class="list-inline-item"><a href="https://www.instagram.com/portalhaus.cl/" target="_blank" title="instagram" class="text-white"><i class="fab fa-instagram">           </i></a></li>
        </ul>
      </div>
    </div>
