<body class="one-screen-page bg-image-4">
    <div class="ie-panel"><a href="https://windows.microsoft.com/en-US/internet-explorer/"><img src="images/ie8-panel/warning_bar_0000_us.jpg" height="42" width="820" alt="You are using an outdated browser. For a faster, safer browsing experience, upgrade for free today."></a></div>
    <!-- Page-->
    <div class="page text-center">
      <!-- Page Header-->
      <header class="page-head"><a class="rd-navbar-brand brand" href="index.html">
          <div class="brand-logo">
            <svg x="0px" y="0px" width="157px" height="41px" viewbox="0 0 157 41">
              <text transform="matrix(1 0 0 1 1.144409e-004 32)" fill="#2C2D2F" font-family="'Grand Hotel'" font-size="45.22">QuickFood</text>
              <path fill-rule="evenodd" clip-rule="evenodd" fill="#EB5453" d="M43.743,2.954c2.606,0,4.719,2.091,4.719,4.672  c0,2.58-2.113,4.672-4.719,4.672c-2.606,0-4.719-2.091-4.719-4.672C39.024,5.045,41.137,2.954,43.743,2.954z"></path>
            </svg>
          </div></a></header>
      <!-- Page Content-->
      <main class="page-content">
        <section>
          <div class="container">
            <div class="row no-gutters justify-content-xs-center">
              <div class="col-sm-10 col-lg-6">
                <h4 class="font-default">Service is temporary unavailable</h4>
                <hr class="hr divider-sm bg-primary-lighter">
                <p class="text-extra-large font-weight-light">503</p>
                <p class="offset-top-40">Sorry, we're offline right now to make our site even better. Please, come back later <br class="visible-lg-inline"> and check what we've been up to.</p>
                <div class="group-lg offset-top-30"><a class="btn btn-primary btn-shape-circle btn-icon-left btn-icon" href="index.html"><span class="icon text-middle mdi mdi-arrow-left text-black"></span><span class="text-black">back to home page</span></a><a class="btn btn-white-outline btn-shape-circle btn-icon-left btn-icon" href="contacts.html"><span class="icon text-middle mdi mdi-email-outline"></span><span>contact us</span></a></div>
              </div>
            </div>
          </div>
        </section>
      </main>
