      <main class="page-content">
        <section class="section-50 section-sm-100">
          <div class="container">
            <h5>Agregar Nuevo Producto</h5>
            <div class="row justify-content-xs-center offset-top-15">
              <div class="col-sm-10 col-md-8">
                <div class="inset-lg-left-50 inset-lg-right-50">
                  <!-- RD Mailform-->
                  <form class="rd-mailform form-contact-line text-left" data-form-output="form-output-global" data-form-type="contact" method="post" action="bat/rd-mailform.php" novalidate="novalidate">
                    <div class="form-inline-flex">
                      <div class="form-group">
                        <label class="form-label form-label-outside rd-input-label" for="contact-name-2">Producto</label>
                        <input class="form-control form-control-has-validation form-control-last-child" id="contact-name-2" type="text" placeholder="Nombre Producto" name="name" data-constraints="@Required"><span class="form-validation"></span>
                      </div>
                      <div class="form-group">
                        <label class="form-label form-label-outside rd-input-label" for="contact-username">Categoria</label>
                        <input class="form-control form-control-has-validation form-control-last-child" id="contact-username" type="text" placeholder="Categoría" name="password" data-constraints="@Required"><span class="form-validation"></span>
                      </div>
                    </div>
                    <div class="form-group offset-top-15">
                      <label class="form-label form-label-outside rd-input-label" for="message">Descripción</label>
                      <textarea class="form-control form-control-has-validation form-control-last-child" id="message" placeholder="Descripción del Producto" name="message" data-constraints="@Required"></textarea><span class="form-validation"></span>
                    </div>
                    <div class="offset-top-15">
                      <div class="form-inline-flex">
                        <div class="form-group has-error">
                          <label class="form-label form-label-outside rd-input-label" for="contact-email-2">Precio</label>
                          <input class="form-control form-control-has-validation form-control-last-child" id="contact-email-2" type="email" placeholder="Precio" name="email" data-constraints="@Email @Required"><span class="form-validation">The text field is required.</span>
                        </div>
                        <div class="form-group">
                          <button class="btn btn-primary-lighter btn-fullwidth" type="submit">Grabar</button>
                        </div>
                      </div>
                    </div>
                  </form>
                </div>
              </div>
            </div>
          </div>
        </section>
      </main>
