<!-- Page Footer -->
      <footer class="page-foot text-sm-left">
        <section class="bg-gray-darker section-top-55 section-bottom-60">
          <div class="container">
            <div class="row border-left-cell">
              <div class="col-sm-6 col-md-3 col-lg-4"><a class="brand brand-inverse" href="index.html">
                  <svg x="0px" y="0px" width="157px" height="52px" viewbox="0 0 157 52">
                    <text transform="matrix(1 0 0 1 1.144409e-004 32)" fill="#2C2D2F" font-family="'Grand Hotel'" font-size="45.22">BigMamma</text>
                    <path fill-rule="evenodd" clip-rule="evenodd" fill="#EB5453" d="M43.743,2.954c2.606,0,4.719,2.091,4.719,4.672  c0,2.58-2.113,4.672-4.719,4.672c-2.606,0-4.719-2.091-4.719-4.672C39.024,5.045,41.137,2.954,43.743,2.954z"></path>
                  </svg></a>
                <ul class="list-unstyled contact-info offset-top-5">
                  <li>
                    <div class="unit unit-horizontal unit-top unit-spacing-xxs">
                      <div class="unit-left"><span class="text-white">Dirección:</span></div>
                      <div class="unit-body text-left text-gray-light">
                        <p>Jose Leyan 683 local 2, Talagante</p>
                      </div>
                    </div>
                  </li>
                  <li>
                    <div class="unit unit-horizontal unit-top unit-spacing-xxs">
                      <div class="unit-left"><span class="text-white">Email:</span></div>
                      <div class="unit-body"><a class="link-gray-light" href="mailto:#">info@bigmamma.cl</a></div>
                    </div>
                  </li>
                </ul>
              </div>
              <div class="col-sm-6 col-md-3 offset-top-50 offset-sm-top-0">
                <h4 class="text-uppercase">Menú</h4>
                <ul class="list-tags offset-top-15">
                  <li class="text-gray-light"><a class="link-gray-light" href="menu-single.html">Hamburguesas</a></li>
                  <li class="text-gray-light"><a class="link-gray-light" href="menu-single.html">Pizzas</a></li>
                  <li class="text-gray-light"><a class="link-gray-light" href="menu-single.html">Sandwichs</a></li>
                  <li class="text-gray-light"><a class="link-gray-light" href="menu-single.html">Ensaladas</a></li>
                  <li class="text-gray-light"><a class="link-gray-light" href="menu-single.html">Bebidas</a></li>
                  <li class="text-gray-light"><a class="link-gray-light" href="menu-single.html">Postres</a></li>
                </ul>
              </div>
              <div class="col-sm-10 col-lg-5 offset-top-50 offset-md-top-0 col-md-6">
                <h4 class="text-uppercase">newsletter</h4>
                <div class="offset-top-20">
                        <form class="rd-mailform form-subscribe form-inline-flex-xs" data-form-output="form-output-global" data-form-type="subscribe" method="post" action="bat/rd-mailform.php">
                          <div class="form-group">
                            <input class="form-control" placeholder="Your Email" type="email" name="email" data-constraints="@Required @Email">
                          </div>
                          <button class="btn btn-burnt-sienna btn-shape-circle" type="submit">Suscribete</button>
                        </form>
                </div>
              </div>
            </div>
          </div>
        </section>
        <section class="section-20 bg-white">
          <div class="container">
            <div class="row justify-content-xs-center justify-content-sm-between">
              <div class="col-sm-5 offset-top-26 text-md-left">
                <p class="copyright">
                  Digital Experience Solution Inc.
                  &nbsp;&#169;&nbsp;<span class="copyright-year"></span>&nbsp;<br class="veil-sm"><a href="privacy.html">Privacy Policy</a>
                  <!-- {%FOOTER_LINK}-->
                </p>
              </div>
              <div class="col-sm-4 offset-top-30 offset-sm-top-0 text-md-right">
                <ul class="list-inline list-inline-sizing-1">
                  <li><a class="link-silver-light" href="#"><span class="icon icon-xs fa-instagram"></span></a></li>
                  <li><a class="link-silver-light" href="#"><span class="icon icon-xs fa-facebook"></span></a></li>
                  <li><a class="link-silver-light" href="#"><span class="icon icon-xs fa-twitter"></span></a></li>
                  <li><a class="link-silver-light" href="#"><span class="icon icon-xs fa-google-plus"></span></a></li>
                </ul>
              </div>
            </div>
          </div>
        </section>

      </footer>
    </div>
