<div class="ie-panel"><a href="https://windows.microsoft.com/en-US/internet-explorer/"><img src="/images/ie8-panel/warning_bar_0000_us.jpg" height="42" width="820" alt="You are using an outdated browser. For a faster, safer browsing experience, upgrade for free today."></a></div>
    <!-- Page-->
    <div class="page text-center">
      <!-- Page Header-->
      <header class="page-head">
        <!-- RD Navbar-->
        <div class="rd-navbar-wrap rd-navbar-default">
          <nav class="rd-navbar" data-layout="rd-navbar-fixed" data-sm-layout="rd-navbar-fixed" data-md-device-layout="rd-navbar-fixed" data-lg-layout="rd-navbar-static" data-lg-device-layout="rd-navbar-static" data-stick-up-clone="false" data-md-stick-up-offset="100px" data-lg-stick-up-offset="150px">
            <div class="container container-fluid">
              <div class="rd-navbar-inner">
                <div class="rd-navbar-nav-wrap-outer">
                  <div class="rd-navbar-aside">
                    <div class="rd-navbar-aside-content">
                      <!-- RD Navbar Panel-->
                      <div class="rd-navbar-panel rd-navbar-aside-left">
                        <!-- RD Navbar Toggle-->
                        <button class="rd-navbar-toggle" data-rd-navbar-toggle=".rd-navbar-nav-wrap"><span></span></button>
                        <!-- RD Navbar Brand--><a class="rd-navbar-brand brand" href="/">
                          <div class="brand-logo">
                            <svg x="0px" y="0px" width="207px" height="62px" viewbox="0 0 207 62">
                              <text transform="matrix(1 0 0 1 1.144409e-004 32)" fill="#2C2D2F" font-family="'Grand Hotel'" font-size="60">BigMamma</text>
                              <path fill-rule="evenodd" clip-rule="evenodd" fill="#EB5453" d="M43.743,2.954c2.606,0,4.719,2.091,4.719,4.672  c0,2.58-2.113,4.672-4.719,4.672c-2.606,0-4.719-2.091-4.719-4.672C39.024,5.045,41.137,2.954,43.743,2.954z"></path>
                            </svg>
                          </div></a>
                      </div>
                      <div class="rd-navbar-aside-right">
                        <!-- RD Navbar Aside-->
                        <ul class="list-links list-inline text-left">
                          <li>
                            <div class="unit unit-horizontal unit-middle unit-spacing-xs">
                              <div class="unit-left"><span class="icon icon-circle icon-burnt-sienna icon-xxs mdi mdi-map-marker text-middle"></span></div>
                              <div class="unit-body">
                                <address class="contact-info"><a class="link-default link-xs" href="/dondeestamos/">Jose Leyan 683 local 2 <br class="visible-md visible-lg"> Talagante</a></address>
                              </div>
                            </div>
                          </li>
                          <li>
                            <div class="unit unit-horizontal unit-middle unit-spacing-xs">
                              <div class="unit-left"><span class="icon icon-circle icon-burnt-sienna icon-xxs mdi mdi-phone text-middle"></span></div>
                              <div class="unit-body">
                                <address class="contact-info"><a class="link-default link-xs" href="tel:+56 9 4119 0183
">+56 9 4119 0183
</a><span class="reveal-block text-base link-xs">Lun – Sab: 13:00–20:30</span></address>
                              </div>
                            </div>
                          </li>
                          <li>
                            <ul class="list-inline list-inline-sm">
                              <li><a class="link-silver-light" href="https://www.instagram.com/bigmamma_talagante/" target="_blank"><span class="icon icon-sm-mod-1 fa fa-instagram"></span></a></li>
                              <li><a class="link-silver-light" href="https://web.facebook.com/bigmammatalagante" target="_blank"><span class="icon icon-sm-mod-1 fa fa-facebook"></span></a></li>
                              <li><a class="link-silver-light" href="#"><span class="icon icon-sm-mod-1 fa fa-twitter"></span></a></li>
                              <li><a class="link-silver-light" href="#"><span class="icon icon-sm-mod-1 fa fa-google-plus"></span></a></li>
                            </ul>
                          </li>
                        </ul>
                      </div>
                    </div>
                  </div>
                </div>
                <!-- RD Navbar Nav-->
                <div class="rd-navbar-nav-wrap">
                  <!-- RD Navbar Shop-->
                  <div class="rd-navbar-shop"><a class="link link-shop link-default" href="/cart/"><span class="big text-gray-light">Carro</span><span class="icon icon-sm mdi mdi-cart-outline"></span><span id="app" @click="Cantidad++" class="label-inline big">{{ Cantidad }}</span></a></div>
                  <!-- RD Navbar Nav-->
                  <ul class="rd-navbar-nav">
                    <li><a href="/">Inicio</a>
                    </li>
                    <li><a href="/micuenta/">Mi Cuenta</a>
                      <ul class="rd-navbar-dropdown rd-navbar-open-right">
                        <li><a href="/micuenta/mispedidos/">Mis Pedidos</a></li>
                        <li><a href="/micuenta/configuracion/">Mi Configuración</a></li>
                      </ul>
                    </li>
                    <li><a href="/menu/">Menu</a>
                      <!-- RD Navbar Dropdown-->
                      <ul class="rd-navbar-dropdown menu-img-wrap">
                        <li class="menu-img"><a href="/menu/"><img src="/images/menu-food-01.png" alt="" width="88" height="60"><span>Pizzas</span></a></li>
                        <li class="menu-img"><a href="/menu/"><img src="/images/menu-food-02.png" alt="" width="88" height="60"><span>Burgers</span></a></li>
                        <li class="menu-img"><a href="/menu/"><img src="/images/menu-food-03.png" alt="" width="88" height="60"><span>Bebidas</span></a></li>
                        <li class="menu-img"><a href="/menu/"><img src="/images/menu-food-04.png" alt="" width="88" height="60"><span>Sandwich</span></a></li>
                        <li class="menu-img"><a href="/menu/"><img src="/images/menu-food-05.png" alt="" width="88" height="60"><span>Ensaladas</span></a></li>
                        <li class="menu-img"><a href="/menu/"><img src="/images/menu-food-06.png" alt="" width="88" height="60"><span>Postres</span></a></li>
                      </ul>
                    </li>
                    <li><a href="/admin/">Administración</a>
                      <ul class="rd-navbar-dropdown rd-navbar-open-right">
                        <li><a href="/admin/catalogo/">Catalogo</a></li>
                        <li><a href="/admin/pedidos/">Pedidos</a></li>
                        <li><a href="/admin/configuracion/">Configuración</a></li>
                      </ul>
                    </li>
                    <li><a href="/nosotros/">Nosotros</a>
                    </li>
                    <!--
                    <li><a href="#">Pages</a>
                      <!-- RD Navbar Megamenu 
                      <ul class="rd-navbar-megamenu">
                        <li>
                          <h6 class="rd-megamenu-header">Pages</h6>
                          <ul class="list-marked">
                            <li><a href="careers.html">Careers</a></li>
                            <li><a href="faq.html">FAQ</a></li>
                            <li><a href="deals.html">Deals</a></li>
                            <li><a href="coming-soon.html">Coming Soon</a></li>
                            <li><a href="404.html">404 Page</a></li>
                            <li><a href="503.html">503 Page</a></li>
                            <li><a href="search-results.html">Search Result</a></li>
                            <li><a href="maintenance.html">Maintenance Page</a></li>
                            <li><a href="privacy.html">Terms of Use</a></li>
                            <li><a href="member-profile.html">Member profile</a></li>
                            <li><a href="team.html">Our Team</a></li>
                            <li><a href="testimonials.html">Testimonials</a></li>
                          </ul>
                        </li>
                        <li>
                          <h6 class="rd-megamenu-header">Additional Pages</h6>
                          <ul class="list-marked">
                            <li><a href="typography.html">Typography</a></li>
                            <li><a href="buttons.html">Buttons</a></li>
                            <li><a href="forms.html">Forms</a></li>
                            <li><a href="icons.html">Icons</a></li>
                            <li><a href="grid.html">Grid</a></li>
                            <li><a href="tabs-and-accordions.html">Tabs &amp; Accordions</a></li>
                            <li><a href="progress-bars.html">Progress Bars</a></li>
                            <li><a href="tables.html">Tables</a></li>
                            <li><a href="login-register.html">Login/Register </a></li>
                          </ul>
                        </li>
                        <li>
                          <h6 class="rd-megamenu-header">Layouts</h6>
                          <ul class="list-marked">
                            <li><a href="index.html">Default Header</a></li>
                            <li><a href="index-corporate.html">Corporate Header</a></li>
                            <li><a href="index-sidebar.html">Sidebar Header</a></li>
                          </ul>
                          <h6 class="rd-megamenu-header">Menu</h6>
                          <ul class="list-marked">
                            <li><a href="menu-classic.html">Menu Classic</a></li>
                            <li><a href="menu-modern.html">Menu Modern</a></li>
                            <li><a href="/menu/">Menu Single</a></li>
                            <li><a href="shop-single.html">Product Single</a></li>
                            <li><a href="shop-cart.html">Cart page</a></li>
                          </ul>
                        </li>
                      </ul>
                    </li> -->
                    <!-- 
                    <li><a href="#">Gallery</a>
                      <!-- RD Navbar Dropdown
                      <ul class="rd-navbar-dropdown">
                        <li><a href="gallery-grid.html">Grid Gallery</a>
                        </li>
                        <li><a href="gallery-cobbles.html">Cobbles Gallery</a>
                        </li>
                        <li><a href="gallery-masonry.html">Masonry Gallery</a>
                        </li>
                        <li><a href="gallery-condensed.html">Grid without Padding</a>
                        </li>
                      </ul>
                    </li>
                    <li><a href="contacts.html">Contacts</a>
                    </li> -->
                    <!-- 
                    <li><a href="#">News</a>
                      <!-- RD Navbar Dropdown
                      <ul class="rd-navbar-dropdown">
                        <li><a href="blog-classic.html">Classic Blog</a>
                        </li>
                        <li><a href="blog-grid.html">Grid Blog</a>
                        </li>
                        <li><a href="blog-masonry.html">Masonry Blog</a>
                        </li>
                        <li><a href="blog-modern.html">Modern Blog</a>
                        </li>
                        <li><a href="post.html">Single Post</a>
                        </li>
                      </ul>
                    </li> -->
                  </ul>
                  <div class="rd-navbar-aside-right">
                    <ul class="list-links list-inline text-left">
                      <li>
                        <div class="unit unit-horizontal unit-middle unit-spacing-xs">
                          <div class="unit-left"><span class="icon icon-circle icon-burnt-sienna icon-xxs mdi mdi-map-marker text-middle"></span></div>
                          <div class="unit-body">
                            <address class="contact-info"><a class="link-default link-xs" href="#">Jose Leyan 683 local 2<br class="visible-md visible-lg">Tagalante</a></address>
                          </div>
                        </div>
                      </li>
                      <li>
                        <div class="unit unit-horizontal unit-middle unit-spacing-xs">
                          <div class="unit-left"><span class="icon icon-circle icon-burnt-sienna icon-xxs mdi mdi-phone text-middle"></span></div>
                          <div class="unit-body">
                            <address class="contact-info"><a class="link-default link-xs" href="tel:+56 9 4119 0183">+56 9 4119 0183</a><span class="reveal-block text-base link-xs">Lun – Sab: 13:00–20:30</span></address>
                          </div>
                        </div>
                      </li>
                      <li>
                        <ul class="list-inline list-inline-sm">
                          <li><a class="link-silver-light" href="#"><span class="icon icon-sm-mod-1 fa fa-instagram"></span></a></li>
                          <li><a class="link-silver-light" href="#"><span class="icon icon-sm-mod-1 fa fa-facebook"></span></a></li>
                          <li><a class="link-silver-light" href="#"><span class="icon icon-sm-mod-1 fa fa-twitter"></span></a></li>
                          <li><a class="link-silver-light" href="#"><span class="icon icon-sm-mod-1 fa fa-google-plus"></span></a></li>
                        </ul>
                      </li>
                    </ul>
                  </div>
                </div>
              </div>
            </div>
          </nav>
        </div>
      </header>
