      <!-- Page Content-->
      <main class="page-content">
        <!-- Breadcrumbs & Page title
        <section class="text-center section-34 section-sm-60 section-md-top-100 section-md-bottom-105 bg-image bg-image-breadcrumbs">
          <div class="container">
            <div class="row no-gutters">
              <div class="col-xs-12 col-xl-preffix-1 col-xl-11">
                <p class="h3 text-white">Login/Register</p>
                <ul class="breadcrumbs-custom offset-top-10">
                  <li><a href="index.html">Home</a></li>
                  <li><a href="#">Pages</a></li>
                  <li class="active">Login/Register</li>
                </ul>
              </div>
            </div>
          </div>
        </section>-->

        <!-- Buttons-->
        <section class="bg-white text-center section-50 section-sm-100">
          <div class="container">
            <div class="row justify-content-xs-center">
              <div class="col-sm-8 col-lg-6">
                <div class="responsive-tabs responsive-tabs-modern responsive-tabs-modern-mod-1 responsive-tabs-horizontal">
                  <ul class="resp-tabs-list">
                    <li>Login</li>
                    <li>Registration</li>
                  </ul>
                  <div class="resp-tabs-container">
                    <div>
                      <div class="group-sm"><a class="btn btn-facebook btn-icon btn-icon-left" href="#"><span class="icon icon-xs fa-facebook"></span><span>Facebook</span></a><!--<a class="btn btn-twitter btn-icon btn-icon-left" href="#"><span class="icon icon-xs fa-twitter"></span><span>Twitter</span></a>--><a class="btn btn-google-plus btn-icon btn-icon-left" href="#"><span class="icon icon-xs fa-google-plus"></span><span>Google +</span></a></div>
                      <div class="divider-custom offset-top-30">
                        <p class="small text-uppercase">Or</p>
                      </div>
                      <!-- RD Mailform-->
                      <form class="rd-mailform form-register text-center offset-top-20">
                        <div class="form-group">
                          <label class="form-label form-label-outside" for="contact-name">Username or E-mail</label>
                          <input class="form-control" id="contact-name" type="text" name="name" data-constraints="@Required">
                        </div>
                        <div class="form-group">
                          <label class="form-label form-label-outside" for="contact-email">Password</label>
                          <input class="form-control" id="contact-email" type="password" name="password" data-constraints="@Required">
                        </div>
                        <div class="offset-top-50">
                          <button class="btn btn-primary-lighter btn-fullwidth btn-shadow" type="submit">Enter</button>
                        </div>
                      </form>
                    </div>
                    <div>
                      <div class="group-sm"><a class="btn btn-facebook btn-icon btn-icon-left" href="#"><span class="icon icon-xs fa-facebook"></span><span>Facebook</span></a><a class="btn btn-twitter btn-icon btn-icon-left" href="#"><span class="icon icon-xs fa-twitter"></span><span>Twitter</span></a><a class="btn btn-google-plus btn-icon btn-icon-left" href="#"><span class="icon icon-xs fa-google-plus"></span><span>Google +</span></a></div>
                      <div class="divider-custom offset-top-30">
                        <p class="small text-uppercase">Or</p>
                      </div>
                      <!-- RD Mailform-->
                      <form class="rd-mailform form-register text-center offset-top-20">
                        <div class="form-group">
                          <label class="form-label form-label-outside" for="register-form-name">Name</label>
                          <input class="form-control" id="register-form-name" type="text" name="name" data-constraints="@Required">
                        </div>
                        <div class="form-group">
                          <label class="form-label form-label-outside" for="register-form-email">E-mail</label>
                          <input class="form-control" id="register-form-email" type="email" name="email" data-constraints="@Required @Email">
                        </div>
                        <div class="form-group">
                          <label class="form-label form-label-outside" for="register-form-password">Password</label>
                          <input class="form-control" id="register-form-password" type="password" name="password" data-constraints="@Required">
                        </div>
                        <div class="form-group">
                          <label class="form-label form-label-outside" for="register-form-password-confirm">Confirm Password</label>
                          <input class="form-control" id="register-form-password-confirm" type="password" name="password-confirm" data-constraints="@Required">
                        </div>
                        <div class="offset-top-50">
                          <button class="btn btn-primary-lighter btn-fullwidth btn-shadow" type="submit">Register</button>
                        </div>
                      </form>
                    </div>
                  </div>
                </div>
              </div>
            </div>
          </div>
        </section>

      </main>