<?php 

$message = array(
    		'en' => array('title' => 'Digital Commerce',
    				 'message1' => 'to sell your products and services globally',
    				 'message2' => 'We launched our Machine Learning Automated Commerce for any industry. Instant Provisioning.',
    				 'startnow' => 'START NOW',
    				 'features' => 'FEATURES',
    				 'pricing' => 'PRICING',
    				 'home' => 'HOME',
    				 'lang' => 'English',
    				 'contact' => 'CONTACT',
    				 'login' => 'LOGIN',
    				 'getstarted' => 'GET STARTED',
                     'message3' => 'Start now your E-commerce in seconds with',
                     'description1' => 'The most advanced and automated E-commerce Platform provides a full experience with which users can manage the offers of products and services of their online business',
                     'message4' => 'Overcome Geographical Limitations',
                     'message5' => 'Remain Open All the Time',
                     'message6' => 'Sell more and Improve your User Experience',
                     'message7' => 'Reduce your OPEX'), 
    		'fr' => array('title' => 'Digital Commerce',
    				 'message1' => 'pour vendre vos produits et services dans le monde entier',
    				 'message2' => 'Nous avons lancé notre commerce automatisé d\'apprentissage automatique pour tous les secteurs. Approvisionnement instantanément.',
    				 'startnow' => 'COMMENCEZ MAINTENANT',
    				 'features' => 'FONCTIONNALITÉS',
    				 'pricing' => 'TARIFICATION',
    				 'home' => 'ACCUEIL',
    				 'lang' => 'Français',
    				 'contact' => 'CONTACT',
    				 'login' => 'S\'IDENTIFIER',
    				 'getstarted' => 'COMMENCER',
                     'message3' => 'Start now your E-commerce in seconds with',
                     'description1' => 'The most advanced and automated E-commerce Platform provides a full experience with which users can manage the offers of products and services of their online business',
                     'message4' => 'Overcome Geographical Limitations',
                     'message5' => 'Remain Open All the Time',
                     'message6' => 'Sell more and Improve your User Experience',
                     'message7' => 'Reduce your OPEX'),
    		'de' => array('title' => 'Digital Commerce',
    				 'message1' => 'um Ihre Produkte und Dienstleistungen weltweit zu verkaufen',
    				 'message2' => "Wir haben unseren automatisierten Handel für maschinelles Lernen für jede Branche eingeführt. Sofortige Bereitstellung.",
    				 'startnow' => 'JETZT ANFANGEN',
    				 'features' => 'FUNKTIONALITÄTEN',
    				 'pricing' => 'TARIFICATION',
    				 'home' => 'ACCUEIL',
    				 'lang' => 'Deutsche',
    				 'contact' => 'CONTACT',
    				 'login' => 'ANMELDUNG',
    				 'getstarted' => 'LOSLEGEN',
                     'message3' => 'Start now your E-commerce in seconds with',
                     'description1' => 'The most advanced and automated E-commerce Platform provides a full experience with which users can manage the offers of products and services of their online business',
                     'message4' => 'Overcome Geographical Limitations',
                     'message5' => 'Remain Open All the Time',
                     'message6' => 'Sell more and Improve your User Experience',
                     'message7' => 'Reduce your OPEX'),
    		'es' => array('title' => 'Digital Commerce', 'message1' => 'para vender tus productos y servicios globalmente',
    			'message2' => 'Lanzamos nuestro Commerce con Machine Learning automático para cualquier industria. Se provisiona instantatemente.',
    			'startnow' => 'COMIENZA AHORA',
    			'features' => 'CARACTERISTICAS',
    			'pricing' => 'PRECIOS',
    			'home' => 'INICIO',
    			'lang' => 'Español',
    			'contact' => 'CONTACTO',
    			'login' => 'INICIAR SESIÓN',
    			'getstarted' => 'EMPEZAR',
                'message3' => 'Inicie su comercio electrónico en segundos con',
                     'description1' => 'The most advanced and automated E-commerce Platform provides a full experience with which users can manage the offers of products and services of their online business',
                     'message4' => 'Overcome Geographical Limitations',
                     'message5' => 'Remain Open All the Time',
                     'message6' => 'Sell more and Improve your User Experience',
                     'message7' => 'Reduce your OPEX'),
    		'pt' => array('title' => 'Digital Commerce', 'message1' => 'para vender seus produtos e serviços globalmente',
    			'message2' => 'Lançamos nosso Machine Learning Automated Commerce para qualquer setor. Provisionamento instantaneamente',
    			'startnow' => 'COMECE AGORA',
    			'features' => 'CARACTERÍSTICAS',
    			'pricing' => 'PREÇOS',
    			'home' => 'COMEÇAR',
    			'lang' => 'Português',
    			'contact' => 'CONTATO',
    			'login' => 'CONECTE-SE',
    			'getstarted' => 'INICIAR'),
    		'cn' => array('title' => 'Digital Commerce', 'message1' => '在全球范围内销售您的产品和服务',
    			'message2' => '我们针对任何行业推出了带有自动机器学习功能的Commerce。 它是即时配置的。',
    			'startnow' => '现在开始',
    			'features' => '特征',
    			'pricing' => '价格',
    			'home' => '开始',
    			'lang' => '中文',
    			'contact' => '联系',
    			'login' => '登录',
    			'getstarted' => '开始'),
    		'jp' => array('title' => 'Digital Commerce', 'message1' => '製品やサービスをグローバルに販売する',
    			'message2' => 'あらゆる業界向けに機械学習自動コマースを開始しました。 インスタントプロビジョニング。',
    			'startnow' => '今すぐ始める',
    			'features' => '特徴',
    			'pricing' => '价格',
    			'home' => 'ホームホーム',
    			'lang' => '日本人',
    			'contact' => '連絡先',
    			'login' => 'ログインする',
    			'getstarted' => '始めましょう'),
    		'it' => array('title' => 'Digital Commerce', 'message1' => 'per vendere i tuoi prodotti e servizi a livello globale',
    			'message2' => 'Abbiamo lanciato il nostro commercio con machine learning automatico per qualsiasi settore. Viene fornito istantaneamente.',
    			'startnow' => 'INIZIA ORA',
    			'features' => 'CARATTERISTICHE',
    			'pricing' => 'PREZZI',
    			'home' => 'INIZIO',
    			'lang' => 'Italiano',
    			'contact' => 'CONTATTO',
    			'login' => 'ACCESSO',
    			'getstarted' => 'INIZIO')
    		);
?>