<!DOCTYPE html>
<html lang="<?php echo $language."-".$country; ?>">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <title>Digital Experience Solution Inc | DXS</title>
    <meta name="author" content="DXS.Cloud" />
    <meta name="description" content="Digital Experience Solution Inc | Cloud Applications" />
    <meta name="keywords" content="DXS Digital Experience Solution Cloud Applications" />
    <meta property="og:url" content="https://dxs.cloud" />
    <meta property="og:type" content="website" />
    <meta property="og:title" content="" />
    <meta property="og:description" content="Digital Commerce to sell your products and services globally" />
    <meta property="og:image" content="https://www.code-brew.com/wp-content/uploads/2019/08/img_6.png" />
    <meta property="og:image:secure_url" content="https://www.code-brew.com/wp-content/uploads/2019/08/img_6.png" />
    <meta name="viewport" content="width=device-width,initial-scale=1,user-scalable=yes">
    <meta name="robots" content="index,follow" />
    <meta name="author" content="Digital Experience Solution Inc" />
    <meta name="copyright" content="Digital Experience Solution Inc" />
    <!-- Prefetch DNS for external assets -->
    <link rel="dns-prefetch" href="//fonts.googleapis.com">
    <link rel="dns-prefetch" href="//www.google-analytics.com">
    <link rel="dns-prefetch" href="//www.googletagmanager.com">
    <link rel="sitemap" type="application/xml" title="sitemap" href="https://dxs.cloud/sitemap/">
    <link rel="canonical" href="https://dxs.cloud<?php echo $_SERVER["REQUEST_URI"]; ?>">
    <!-- Global site tag (gtag.js) - Google Analytics -->
    
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="stylesheet" href="/css/swiper.css">
    <link rel="stylesheet" href="/style.css">
    <link href="https://fonts.googleapis.com/css?family=Source+Sans+Pro:300,400,700,900" rel="stylesheet"> 
    <link rel="icon" type="image/svg" href="/favicon.svg">
    <!-- Tweaks for older IEs-->
    <!--[if lt IE 9]>
        <script defer src="https://oss.maxcdn.com/html5shiv/3.7.3/html5shiv.min.js"></script>
        <script defer src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script><![endif]-->
    <!-- Font Awesome CSS-->
</head>
<?php echo $this->getContent(); ?>
</body>
</html>
<!-- Digital Experience Solution Inc - 2020 - US/Chile -->
